# Generated by Django 5.2.7 on 2026-09-24 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("masters", "0002_initial"),
        ("sales", "0002_alter_paymentin_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentin",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentin",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="sales.salesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="paymentin",
            name="payment_type",
            field=models.TextField(
                choices=[
                    ("WITH_BILL", "With Bill"),
                    ("WITHOUT_BILL", "Without Bill / Cash"),
                ],
                default="WITH_BILL",
            ),
        ),
        migrations.CreateModel(
            name="CashPaymentReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("receipt_number", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("payment_date", models.DateField()),
                (
                    "mode",
                    models.TextField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank", "Bank"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Card", "Card"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Bank Wire", "Bank Wire"),
                            ("ACH", "ACH"),
                            ("Corporate Card", "Corporate Card"),
                        ],
                        default="Cash",
                    ),
                ),
                ("reference_number", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                            ("VOIDED", "Voided"),
                        ],
                        default="RECEIVED",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_receipts",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_receipts",
                        to="masters.party",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_receipt",
                        to="sales.paymentin",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cash_payment_receipts",
                "ordering": ["-payment_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("client", "receipt_number"),
                        name="uq_cash_receipt_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="ck_cash_receipt_amount",
                    ),
                ],
            },
        ),
    ]
