# Generated by Django 5.2.7 on 2026-09-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_paymentin_sales_order_salesorder_cash_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentin",
            name="proforma_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_receipts",
                to="sales.proformainvoice",
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="cash_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="formal_invoice_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="total_sales_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
