# Generated by Django 5.2.7 on 2026-09-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_paymentin_proforma_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverychallan",
            name="status",
            field=models.TextField(
                choices=[
                    ("Draft", "Draft"),
                    ("Dispatched", "Dispatched"),
                    ("In Transit", "In Transit"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
            ),
        ),
    ]
