# Generated by Django 5.2.7 on 2026-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_quotation_commercial_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallanline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliverychallanline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverychallanline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverychallanline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="estimateline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="estimateline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimateline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimateline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoiceline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoiceline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Fabrication", "Fabrication"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="material_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="unit_weight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
    ]
