# Generated by Django 5.2.7 on 2026-09-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_sales_line_metal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallan",
            name="gross_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="net_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="tare_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="weighbridge_slip",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverychallanline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimateline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoiceline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="sheet_spec",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliverychallanline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="estimateline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoiceline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="line_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sheet Metal", "Sheet Metal"),
                    ("Section / Pipe", "Section / Pipe"),
                    ("Fabrication", "Fabrication"),
                    ("Machine", "Machine"),
                    ("Spare Part", "Spare Part"),
                    ("Service", "Service"),
                    ("Custom", "Custom"),
                ],
                null=True,
            ),
        ),
    ]
