# Generated by Django 5.2.7 on 2026-10-07 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_menu_organization_permission"),
        ("sales", "0010_sheet_metal_spec_and_weighbridge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesApprovalLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doc_type",
                    models.TextField(
                        choices=[
                            ("estimate", "Estimate"),
                            ("quotation", "Quotation"),
                            ("proforma_invoice", "Proforma invoice"),
                            ("sales_invoice", "Sales invoice"),
                        ]
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("document_number", models.TextField(blank=True, null=True)),
                ("token_hash", models.TextField(unique=True)),
                ("recipient_name", models.TextField(blank=True, null=True)),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("Active", "Active"),
                            ("Revoked", "Revoked"),
                            ("Expired", "Expired"),
                        ],
                        default="Active",
                    ),
                ),
                (
                    "decision",
                    models.TextField(
                        blank=True,
                        choices=[("Approved", "Approved"), ("Rejected", "Rejected")],
                        null=True,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.TextField(blank=True, null=True)),
                ("decision_comments", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_approval_links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesApprovalComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doc_type",
                    models.TextField(
                        choices=[
                            ("estimate", "Estimate"),
                            ("quotation", "Quotation"),
                            ("proforma_invoice", "Proforma invoice"),
                            ("sales_invoice", "Sales invoice"),
                        ]
                    ),
                ),
                ("document_id", models.UUIDField()),
                (
                    "author_type",
                    models.TextField(
                        choices=[("Staff", "Staff"), ("Client", "Client")],
                        default="Staff",
                    ),
                ),
                ("author_name", models.TextField(blank=True, null=True)),
                ("text", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="sales.salesapprovallink",
                    ),
                ),
            ],
            options={
                "db_table": "sales_approval_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="salesapprovallink",
            index=models.Index(
                fields=["doc_type", "document_id"], name="ix_sales_approval_links_doc"
            ),
        ),
        migrations.AddIndex(
            model_name="salesapprovalcomment",
            index=models.Index(
                fields=["doc_type", "document_id", "created_at"],
                name="ix_sales_approval_comments",
            ),
        ),
    ]
