# Generated by Django 5.2.7 on 2026-10-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_sales_approval_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="converted_challan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sales.deliverychallan",
            ),
        ),
    ]
