# Generated by Django 5.2.7 on 2026-10-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_item_has_tube_spec_item_metal_grade_and_more"),
        ("sales", "0012_estimate_converted_challan"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallan",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimate",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="is_one_time_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="party_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="party_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="party_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliverychallan",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.party",
            ),
        ),
    ]
