# Generated by Django 5.2.7 on 2026-09-28 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_party"),
        ("hrms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="first_punch",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="last_punch",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="source",
            field=models.TextField(
                choices=[
                    ("manual", "manual"),
                    ("bulk", "bulk"),
                    ("biometric", "biometric"),
                    ("regularization", "regularization"),
                    ("leave", "leave"),
                    ("holiday", "holiday"),
                    ("punch", "punch"),
                ],
                default="manual",
            ),
        ),
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("work_date", models.DateField(db_index=True)),
                (
                    "punch_type",
                    models.CharField(
                        choices=[("IN", "Punch In"), ("OUT", "Punch Out")],
                        max_length=10,
                    ),
                ),
                ("punch_time", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web / Topbar"),
                            ("mobile", "Mobile App"),
                            ("biometric", "Biometric Device"),
                            ("manual", "Manual / Correction"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punches",
                        to="hrms.attendance",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punches",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_attendance_punches",
                "ordering": ["punch_time"],
                "indexes": [
                    models.Index(
                        fields=["client", "employee", "work_date"],
                        name="ix_hrms_punch_emp_date",
                    ),
                    models.Index(
                        fields=["client", "punch_time"], name="ix_hrms_punch_time"
                    ),
                ],
            },
        ),
    ]
