# Generated by Django 5.2.7 on 2026-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_attendance_first_punch_attendance_last_punch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
