# Generated by Django 5.2.7 on 2026-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0003_attendance_early_leaving_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.TextField(
                choices=[
                    ("Headquarters", "Headquarters"),
                    ("Branch", "Branch"),
                    ("Factory", "Factory"),
                    ("Warehouse", "Warehouse"),
                    ("Remote", "Remote"),
                ],
                default="Branch",
            ),
        ),
    ]
