# Generated by Django 5.2.7 on 2026-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_meetingroom_companymeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
    ]
