# Generated by Django 5.2.7 on 2026-09-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresetotp"),
        ("masters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="masters.party",
            ),
        ),
    ]
