# Generated by Django 5.2.7 on 2026-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="weight_tolerance_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
    ]
