# Generated by Django 5.2.7 on 2026-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0003_party_weight_tolerance_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="has_tube_spec",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="metal_grade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="outer_diameter",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="outer_height",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="outer_width",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sheet_thickness",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sheet_thickness_unit",
            field=models.TextField(blank=True, default="mm", null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="tube_length",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tube_profile",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Round", "Round"),
                    ("Square", "Square"),
                    ("Rectangular", "Rectangular"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="wall_thickness",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="weight_per_meter",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="weight_per_piece",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="dimension_unit",
            field=models.TextField(blank=True, default="mm", null=True),
        ),
    ]
