# Generated by Django 5.2.7 on 2026-10-09 10:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_menu_organization_permission"),
        ("masters", "0004_item_has_tube_spec_item_metal_grade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("family", models.TextField(default="Mild Steel")),
                (
                    "density",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("7.8500"), max_digits=8
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "material_grades",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="default_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="masters.unit",
            ),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="default_uom",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("shape_profile", models.TextField(blank=True, null=True)),
                ("dimension_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "item_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="masters.itemtype",
            ),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="masters.itemtype",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["client", "name"], name="ix_item_categories_name"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["client", "item_type"], name="ix_item_categories_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("item_type__isnull", False)
                ),
                fields=("client", "item_type", "name"),
                name="uq_category_item_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("item_type__isnull", True)
                ),
                fields=("client", "name"),
                name="uq_category_name_no_type",
            ),
        ),
        migrations.AddField(
            model_name="materialgrade",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.client",
            ),
        ),
        migrations.AddField(
            model_name="materialgrade",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialgrade",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialgrade",
            name="material_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="masters.itemcategory",
            ),
        ),
        migrations.AddField(
            model_name="materialgrade",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="masters.materialgrade",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["client", "item_type"],
                name="ix_items_type",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtype",
            index=models.Index(fields=["client", "name"], name="ix_item_types_name"),
        ),
        migrations.AddIndex(
            model_name="itemtype",
            index=models.Index(fields=["client", "code"], name="ix_item_types_code"),
        ),
        migrations.AddConstraint(
            model_name="itemtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("client", "code"),
                name="uq_item_types_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("client", "name"),
                name="uq_item_types_name",
            ),
        ),
        migrations.AddIndex(
            model_name="materialgrade",
            index=models.Index(
                fields=["client", "code"], name="ix_material_grades_code"
            ),
        ),
        migrations.AddIndex(
            model_name="materialgrade",
            index=models.Index(
                fields=["client", "family"], name="ix_material_grades_family"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialgrade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("client", "code"),
                name="uq_material_grades_code",
            ),
        ),
    ]
