# Generated by Django 5.2.7 on 2026-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0006_seed_item_types_and_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="diameter",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="finish_coating",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="flange_thickness",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="inner_diameter",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="leg_a",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="leg_b",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="web_thickness",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
    ]
