# Generated by Django 5.2.7 on 2026-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="currency",
            field=models.TextField(default="INR"),
        ),
    ]
