# Generated by Django 5.2.7 on 2026-10-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="alert_threshold_pct",
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="accounting.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="department_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
