# Generated by Django 5.2.7 on 2026-10-07 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_menu_organization_permission"),
        ("inventory", "0004_reworkorder_scraplog_demounit_and_more"),
        ("masters", "0003_party_weight_tolerance_pct"),
        ("purchase", "0003_expense_project_purchasebill_project_vendoradvance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("inspection_number", models.TextField(unique=True)),
                ("batch_lot_number", models.TextField(blank=True, default="")),
                (
                    "sample_size",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                ("received_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "accepted_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inspection"),
                            ("passed", "Passed & Released"),
                            ("rework", "Under Rework"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("checklist_results", models.JSONField(blank=True, default=list)),
                ("inspector_notes", models.TextField(blank=True, default="")),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_inspections",
                        to="purchase.goodsreceipt",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_inspections",
                        to="masters.item",
                    ),
                ),
                (
                    "rework_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_inspections",
                        to="inventory.reworkorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_inspections",
                "ordering": ["-created_at"],
            },
        ),
    ]
