# Generated by Django 5.2.7 on 2026-10-09 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_menu_organization_permission"),
        ("inventory", "0005_qualityinspection"),
        ("masters", "0007_phase3_metal_item_master_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="ck_movement_reference",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="uom",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="type",
            field=models.TextField(
                choices=[
                    ("OPENING_STOCK", "OPENING_STOCK"),
                    ("PURCHASE", "PURCHASE"),
                    ("PURCHASE_RETURN", "PURCHASE_RETURN"),
                    ("PURCHASE_REVERSAL", "PURCHASE_REVERSAL"),
                    ("SALE", "SALE"),
                    ("SALE_REVERSAL", "SALE_REVERSAL"),
                    ("SALES_RETURN", "SALES_RETURN"),
                    ("RETURN_CANCELLATION", "RETURN_CANCELLATION"),
                    ("TRANSFER_IN", "TRANSFER_IN"),
                    ("TRANSFER_OUT", "TRANSFER_OUT"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("FAULTY", "FAULTY"),
                    ("SERVICE_USAGE", "SERVICE_USAGE"),
                    ("ZONE_ISSUE", "ZONE_ISSUE"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference_id__isnull", False),
                    ("type__in", ["ADJUSTMENT", "OPENING_STOCK"]),
                    _connector="OR",
                ),
                name="ck_movement_reference",
            ),
        ),
    ]
