# Generated by Django 5.2.7 on 2026-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_phase4_stock_ledger_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="type",
            field=models.TextField(
                choices=[
                    ("OPENING_STOCK", "OPENING_STOCK"),
                    ("PURCHASE", "PURCHASE"),
                    ("PURCHASE_RETURN", "PURCHASE_RETURN"),
                    ("PURCHASE_REVERSAL", "PURCHASE_REVERSAL"),
                    ("SALE", "SALE"),
                    ("SALE_REVERSAL", "SALE_REVERSAL"),
                    ("SALES_RETURN", "SALES_RETURN"),
                    ("RETURN_CANCELLATION", "RETURN_CANCELLATION"),
                    ("TRANSFER_IN", "TRANSFER_IN"),
                    ("TRANSFER_OUT", "TRANSFER_OUT"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("FAULTY", "FAULTY"),
                    ("SCRAP", "SCRAP"),
                    ("SERVICE_USAGE", "SERVICE_USAGE"),
                    ("ZONE_ISSUE", "ZONE_ISSUE"),
                    ("MATERIAL_ISSUE", "MATERIAL_ISSUE"),
                ]
            ),
        ),
    ]
