# Generated by Django 5.2.7 on 2026-09-22 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("pms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstage",
            name="weight_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name="projectstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_pct__gte", 0), ("weight_pct__lte", 100)),
                name="ck_pms_stage_weight_pct",
            ),
        ),
    ]
