# Generated by Django 5.2.7 on 2026-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_delegatedtask_projectbug_timesheet_timesheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
