# Generated by Django 5.2.7 on 2026-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="notify_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmproject",
            name="customer_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmproject",
            name="manager_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmproject",
            name="project_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmproject",
            name="team",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="client_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="contact_phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="product",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="source_label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="tag",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadcall",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadcall",
            name="subject",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadproduct",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="leadproduct",
            name="sku",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadproduct",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadsource",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadsource",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
