# Generated by Django 5.2.7 on 2026-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_crm_fields_for_frontend"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="deal",
            name="documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="deal",
            name="line_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="deal",
            name="tax_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
