# Generated by Django 5.2.7 on 2026-09-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_deal_pricing_and_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastertask",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crm.form",
            ),
        ),
        migrations.AddField(
            model_name="stagetask",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crm.form",
            ),
        ),
        migrations.AlterField(
            model_name="stagetask",
            name="master_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stage_tasks",
                to="crm.mastertask",
            ),
        ),
    ]
