# Generated by Django 5.2.7 on 2026-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_task_forms_and_master_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagetask",
            name="max_repeats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
