# Generated by Django 5.2.7 on 2026-10-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_companyprofile_currency"),
        ("crm", "0007_stage_task_max_repeats"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="client_signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_signed_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="company_signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="company_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="company_signed_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="email_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="pdf_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.file",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.TextField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                    ("Active", "Active"),
                    ("Closed", "Closed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
            ),
        ),
    ]
