# Generated by Django 5.2.7 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payment_mode",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank"),
                    ("UPI", "UPI"),
                    ("Cheque", "Cheque"),
                    ("Card", "Card"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Bank Wire", "Bank Wire"),
                    ("ACH", "ACH"),
                    ("Corporate Card", "Corporate Card"),
                    ("Credit", "Credit"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentout",
            name="mode",
            field=models.TextField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank"),
                    ("UPI", "UPI"),
                    ("Cheque", "Cheque"),
                    ("Card", "Card"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Bank Wire", "Bank Wire"),
                    ("ACH", "ACH"),
                    ("Corporate Card", "Corporate Card"),
                ],
                default="Bank",
            ),
        ),
    ]
