# Generated by Django 5.2.7 on 2026-10-07 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_budget_alert_threshold_pct_budget_category_and_more"),
        ("accounts", "0006_menu_organization_permission"),
        ("masters", "0003_party_weight_tolerance_pct"),
        ("pms", "0007_delegatedtask_projectbug_timesheet_timesheetentry"),
        ("purchase", "0002_alter_expense_payment_mode_alter_paymentout_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_expenses",
                to="pms.project",
            ),
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_bills",
                to="pms.project",
            ),
        ),
        migrations.CreateModel(
            name="VendorAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("advance_number", models.TextField()),
                ("advance_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "reconciled_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "mode",
                    models.TextField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank", "Bank"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Card", "Card"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Bank Wire", "Bank Wire"),
                            ("ACH", "ACH"),
                            ("Corporate Card", "Corporate Card"),
                        ],
                        default="Bank",
                    ),
                ),
                ("reference_number", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Disbursed", "Disbursed"),
                            ("Partially Reconciled", "Partially Reconciled"),
                            ("Reconciled", "Reconciled"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Disbursed",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_advances",
                        to="masters.party",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advances",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendor_advances",
                "ordering": ["-advance_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("client", "advance_number"),
                        name="uq_vendor_advances_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="ck_vendor_advance_amount",
                    ),
                ],
            },
        ),
    ]
