# Generated by Django 5.2.7 on 2026-10-07 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_menu_organization_permission"),
        ("masters", "0003_party_weight_tolerance_pct"),
        ("purchase", "0003_expense_project_purchasebill_project_vendoradvance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvanceShippingNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("asn_number", models.TextField(unique=True)),
                ("carrier_name", models.TextField()),
                ("tracking_lr_number", models.TextField()),
                ("vehicle_number", models.TextField(blank=True, default="")),
                ("dispatch_date", models.DateField()),
                ("estimated_arrival", models.DateField()),
                (
                    "dispatch_weight_kg",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("items_dispatched", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In Transit"),
                            ("dock_received", "Dock Received"),
                            ("inspected", "Inspected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_transit",
                        max_length=20,
                    ),
                ),
                ("vendor_notes", models.TextField(blank=True, default="")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asns",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asns",
                        to="masters.party",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_asns",
                "ordering": ["-dispatch_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorPortalUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_id", models.TextField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.TextField()),
                ("phone", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("access_token", models.TextField(blank=True, default="")),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_users",
                        to="masters.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendor_portal_users",
                "ordering": ["name"],
            },
        ),
    ]
