# Generated by Django 5.2.7 on 2026-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_purchasebill_is_one_time_party_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="status",
            field=models.TextField(
                choices=[
                    ("Draft", "Draft"),
                    ("Received", "Received"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Received",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="uom",
            field=models.TextField(blank=True, null=True),
        ),
    ]
